---
- import_role:
    name: service-precheck
  vars:
    service_precheck_services: "{{ dingoops_services }}"
    service_name: "{{ project_name }}"

- name: Get container facts
  become: true
  kolla_container_facts:
    action: get_containers
    container_engine: "{{ kolla_container_engine }}"
    name:
      - dingoops
      - dingoops_console
  register: container_facts

- name: Checking free port for dingoops APIServer
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ dingoops_listen_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['dingoops'] is not defined
    - inventory_hostname in groups['dingoops']

- name: Checking free port for dingoops Console
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ dingoops_console_listen_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['dingoops_console'] is not defined
    - inventory_hostname in groups['dingoops-console']
