---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_dingoops_auth }}"
    service_ks_register_services: "{{ dingoops_ks_services }}"
    service_ks_register_users: "{{ dingoops_ks_users }}"

